// exportActionTypes   (DONT DELETE THIS LINE: USED FOR BATTLECRY DUCK GENERATOR)
export const DELETE_INTERVIEW_CRITERIA = 'interview-criteria/DELETE-INTERVIEW-CRITERIA';
export const ADD_INTERVIEW_CRITERIA = 'interview-criteria/ADD-INTERVIEW-CRITERIA';
export const UPDATE_INTERVIEW_CRITERIA = 'interview-criteria/UPDATE-INTERVIEW-CRITERIA';
export const UPDATE_INTERVIEW_CRITERIAS = 'interview-criteria/UPDATE-INTERVIEW-CRITERIAS';
export const GET_INTERVIEW_CRITERIAS = 'interview-criteria/GET-INTERVIEW-CRITERIAS';
