// exportActionTypes   (DONT DELETE THIS LINE: USED FOR BATTLECRY DUCK GENERATOR)
export const CREATE_EMPLOYEE_TRAINING_TOPICS = 'employee/CREATE-EMPLOYEE-TRAINING-TOPICS';
export const UPDATE_EMPLOYEE_TRAINING = 'employee/UPDATE-EMPLOYEE-TRAINING';
export const GET_EMPLOYEE_TRAININGS = 'employee/GET-EMPLOYEE-TRAININGS';
export const CREATE_EMPLOYEE_TRAINING_HISTORY = 'employee/CREATE-EMPLOYEE-TRAINING-HISTORY';
export const GET_EMPLOYEES = 'employee/GET-EMPLOYEES';
