// exportActionTypes   (DONT DELETE THIS LINE: USED FOR BATTLECRY DUCK GENERATOR)
export const GET_CONSTANTS_PUBLIC = 'constants/GET-CONSTANTS-PUBLIC';
export const GET_CONSTANTS = 'constants/GET-CONSTANTS';
