// exportActionTypes   (DONT DELETE THIS LINE: USED FOR BATTLECRY DUCK GENERATOR)
export const DELETE_TRAINING_CURRICULUM_TOPIC = 'training-curriculum/DELETE-TRAINING-CURRICULUM-TOPIC';
export const ADD_TRAINING_CURRICULUM_TOPIC = 'training-curriculum/ADD-TRAINING-CURRICULUM-TOPIC';
export const GET_TRAINING_CURRICULUM = 'training-curriculum/GET-TRAINING-CURRICULUM';
export const RESET_TRAINING_CURRICULUM = 'training-curriculum/RESET-TRAINING-CURRICULUM';
export const UPSERT_TRAINING_CURRICULUM = 'training-curriculum/UPSERT-TRAINING-CURRICULUM';
export const GET_TRAINING_CURRICULUMS = 'training-curriculum/GET-TRAINING-CURRICULUMS';
